academia/academia/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.usuarios.views import AdminLogin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.alunos.urls')),
    path('', include('apps.equipamentos.urls')),
    path('', include('apps.funcionarios.urls')),
    path('', include('apps.usuarios.urls')),
    path('', AdminLogin.as_view(), name='login'),


]

academia/apps/usuarios/urls.py
from django.urls import path
from .views import AdminLogin, FuncionarioCreate, UsuarioCreate
from django.contrib.auth import views as auth_views
app_name = 'usuarios'

urlpatterns = [
   
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('cadastro-cliente/', UsuarioCreate.as_view(), name='cadastro-cliente'),
    path('cadastrar-funcionario/', FuncionarioCreate.as_view(), name="cadastro-funcionario")
]

academia/templates/sign/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Criar conta</title>

    <!-- Custom fonts for this template-->
    <link href={% static "vendor/fontawesome-free/css/all.min.css" rel="stylesheet" %} type="text/css">
    <link
        href={% static "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" %}
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href={% static "css/sb-admin-2.min.css" %} rel="stylesheet">

</head>

<body class="" style="background-color:darkred;">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Cria uma nova conta!</h1>
                            </div>
                            {% block conteudo %}
                            <form class="user">
                             
                            </form>
                            {% endblock %}
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

academia/templates/sign/sign-in.html
{% extends 'sign/register.html' %}


<title>{% block titulo %} Cadastros {% endblock %} </title>

    {% load crispy_forms_tags %}
    
        {% block conteudo %}

                {% if object.pk %}
                    <h1 class="h3 my-3 text-dark">Editando Cadastro</h1>
                {% else %}
                    <h1 class="h3 my-3 text-dark">Cadastrar Usuário</h1>
                {% endif %}

                    <form method="POST" action="" >
                        <div id="" class="col bg-white rounded p-2">
                            {% csrf_token %}
                            {{ form | crispy }}
                            <div class="text-right col-md-12 ">        
                              
                              
                                <button type="submit" class="save btn text-white " style="background:#198754;">
                                    <! MESMA COISA AQUI, NÃO VOU MECHER COM ISSO AGORA.>
                                    <i class="fas fa-save"></i>
                                    Cadastrar
                                </button>
                                <a class="btn btn-secondary"  href="{% url 'usuarios:login' %}"  style="background:#6c757d;">
                                    <i class="fas fa-arrow-left"></i>
                                    Voltar
                                </a>
                              
        
                            </div>
                        </div> 
                    </form>
               

        {% endblock %}
    